Universite Web/Models/About.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Universite_Web.Models
{
    public class About
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(250)]
        public string Title { get; set; }
        [Column(TypeName ="nText")]
        public string Content { get; set; }
        [MaxLength(250)]
        public string Image { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }
    }
}

Universite Web/Areas/admin/Controllers/AboutsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Universite_Web.Data;
using Universite_Web.Models;

namespace Universite_Web.Areas.admin.Controllers
{
    [Area("admin")]
    [Authorize]

    public class AboutsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public AboutsController(AppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: admin/Abouts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Abouts.ToListAsync());
        }

        // GET: admin/Abouts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var about = await _context.Abouts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (about == null)
            {
                return NotFound();
            }

            return View(about);
        }

        // GET: admin/Abouts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: admin/Abouts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( About about)
        {
            if (ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    if (about.ImageFile != null)
                    {
                        if (about.ImageFile.ContentType == "image/jpeg" || about.ImageFile.ContentType == "image/png")
                        {
                            if (about.ImageFile.Length <= 3000000)
                            {
                                string FileName = Guid.NewGuid() + "-" + about.ImageFile.FileName;
                                string FilePath = Path.Combine(_webHostEnvironment.WebRootPath, "UploadsAbout", FileName);
                                using (var stream = new FileStream(FilePath, FileMode.Create))
                                {
                                    about.ImageFile.CopyTo(stream);
                                }
                                about.Image = FileName;
                                _context.Add(about);
                                await _context.SaveChangesAsync();
                                return RedirectToAction(nameof(Index));

                            }
                            else
                            {
                                ModelState.AddModelError("", "you can choose only 3 mb image file");
                                return View(about);
                            }


                        }
                        else
                        {
                            ModelState.AddModelError("", "you can choose only image file");
                            return View(about);

                        }

                    }
                    else
                    {
                        ModelState.AddModelError("", " choose image file");
                        return View(about);

                    }

                }
              
            }
            return View(about);
        }

        // GET: admin/Abouts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var about = await _context.Abouts.FindAsync(id);
            if (about == null)
            {
                return NotFound();
            }
            return View(about);
        }

        // POST: admin/Abouts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, About about)
        {
            if (id != about.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    if (about.ImageFile != null)
                    {
                        if (about.ImageFile.ContentType == "image/jpeg" || about.ImageFile.ContentType == "image/png")
                        {
                            if (about.ImageFile.Length <= 3000000)
                            {
                                string olddata = Path.Combine(_webHostEnvironment.WebRootPath, "UploadsAbout", about.Image);
                                if (System.IO.File.Exists(olddata))
                                {
                                    System.IO.File.Delete(olddata);
                                }
                                string FileName = Guid.NewGuid() + "-" + about.ImageFile.FileName;
                                string FilePath = Path.Combine(_webHostEnvironment.WebRootPath, "UploadsAbout", FileName);
                                using (var stream = new FileStream(FilePath, FileMode.Create))
                                {
                                    about.ImageFile.CopyTo(stream);
                                }
                                about.Image = FileName;
                                _context.Abouts.Update(about);
                                await _context.SaveChangesAsync();
                                return RedirectToAction(nameof(Index));

                            }
                            else
                            {
                                ModelState.AddModelError("", "you can choose only 3 mb image file");
                                return View(about);
                            }


                        }
                        else
                        {
                            ModelState.AddModelError("", "you can choose only image file");
                            return View(about);

                        }

                    }
                    else
                    {
                        ModelState.AddModelError("", " choose image file");
                        return View(about);

                    }

                }
            }
            return View(about);
        }

        // GET: admin/Abouts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var about = await _context.Abouts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (about == null)
            {
                return NotFound();
            }

            return View(about);
        }

        // POST: admin/Abouts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var about = await _context.Abouts.FindAsync(id);
            string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "UploadsAbout", about.Image);
            if (System.IO.File.Exists(filePath))
            {
                System.IO.File.Delete(filePath);
            }
            _context.Abouts.Remove(about);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AboutExists(int id)
        {
            return _context.Abouts.Any(e => e.Id == id);
        }
    }
}

Universite Web/Areas/admin/Controllers/AccountUserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Universite_Web.Data;
using Universite_Web.Models;
using Universite_Web.ViewModel;

namespace Universite_Web.Areas.admin.Controllers
{
    [Area("admin")]
    [Authorize]

    public class AccountUserController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public AccountUserController(AppDbContext context, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _webHostEnvironment = webHostEnvironment;
        }
       

        public IActionResult Register()
        {
            ViewData["EducationSectionId"] = new SelectList(_context.EducationSections, "Id", "Country");
            //ViewData["FacultyId"] = new SelectList(_context.Faculties, "Id", "Name");
            //ViewData["SpecialtyId"] = new SelectList(_context.Specialty, "Id", "Name");
            ViewBag.FacultyList = _context.Faculties.ToList();
            //ViewData["GroupId"] = new SelectList(_context.Groups, "Id", "Name");
            return View();
        }


        public JsonResult GetSpecialty(int facultyId)
        {  
            var data = _context.Specialty.Where(x => x.FacultyId == facultyId).ToList();
            return Json(data);
        }

        public JsonResult GetGroup(int specialtyId)
        {
            var data = _context.Groups.Where(x => x.SpecialtyId == specialtyId).ToList();
            return Json(data);
        }

        [HttpPost]
        public async Task<IActionResult> Register(VmStudentRegister model)
        {
            if (ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    if (model.ImageFile != null)
                    {
                        if (model.ImageFile.ContentType == "image/jpeg" || model.ImageFile.ContentType == "image/png")
                        {
                            if (model.ImageFile.Length <= 3000000)
                            {
                                string FileName = Guid.NewGuid() + "-" + model.ImageFile.FileName;
                                string FilePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploadss", FileName);
                                using (var stream = new FileStream(FilePath, FileMode.Create))
                                {
                                    model.ImageFile.CopyTo(stream);
                                }
                                model.Image = FileName;
                                

                            }
                            else
                            {
                                ModelState.AddModelError("", "you can choose only 3 mb image file");
                                return View(model);
                            }


                        }
                        else
                        {
                            ModelState.AddModelError("", "you can choose only image file");
                            return View(model);

                        }

                    }
                    else
                    {
                        ModelState.AddModelError("", " choose image file");
                        return View(model);

                    }

                }

                CustomUser user = new CustomUser()
                {
                    Name = model.Name,
                    Surname = model.Surname,
                    Email = model.Email,
                    UserName = model.Email,
                    PhoneNumber = model.Phone,
                    Adress = model.Adress,
                    AtaAdi=model.AtaAdi,
                    PassportNumber=model.PassportNumber,
                    Gender=model.Gender,
                    Money=model.Money,
                    FormEducation=model.FormEducation,
                    DateOfBirth= model.DateOfBirth,
                    AdmissionDate= model.AdmissionDate,
                    DateOfCompletion= model.DateOfCompletion,
                    Image=model.Image,
                    FacultyId=model.FacultyId,
                    SpecialtyId=model.SpecialtyId,
                    EducationSectionId=model.EducationSectionId,
                    GroupId=model.GroupId,
                    SubjectId = (int?)model.SubjectId,
                    IsAdmin = model.IsAdmin,
                    IsStudent=model.IsStudent
             };
                
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, false);
                    return RedirectToAction("index", "home");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                    return View(model);
                }
                _context.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            ViewBag.FacultyList = _context.Faculties.ToList();
            ViewData["GroupId"] = new SelectList(_context.Groups, "Id", "Name");
            ViewData["EducationSectionId"] = new SelectList(_context.EducationSections, "Id", "Country");


            return View(model);
        }
        
    }
}

Universite Web/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Universite_Web.Data;
using Universite_Web.ViewModel;

namespace Universite_Web.Controllers
{
    public class AboutController : Controller
    {
        private readonly AppDbContext _context;

        public AboutController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            VmHome model = new VmHome()
            {
                Totals = _context.Totals.ToList(),
                About = _context.Abouts.FirstOrDefault()
            };

            return View(model);
        }
    }
}

Universite Web/Areas/admin/Views/AccountUser/Index.cshtml
@model Users
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{ }

@foreach (var item in Model.CustomUsers)
{
<a asp-action="about" asp-route-id="@item.Id">@item.Name</a>}



<a asp-action="index"  asp-controller="Home" asp-area="Universite_Web">GOOO HOME</a>

Universite Web/Areas/admin/Views/AccountUser/Login.cshtml
@model VmStudentLogin
@{
    ViewData["Title"] = "Login";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h1>Login</h1>


<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                </div>
                                <form class="user" asp-area="admin" asp-controller="AccountUser" asp-action="login" method="post">
                                    <div asp-validation-summary="All" class="text-danger"></div>
                                    <div class="form-group">
                                        <input type="email" asp-for="@Model.Email" class="form-control form-control-user"
                                               placeholder="Enter Email Address...">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" asp-for="@Model.Password" class="form-control form-control-user"
                                               placeholder="Password">
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-user btn-block">
                                        Login
                                    </button>
                                </form>
                                <hr>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

Universite Web/Areas/admin/Views/AccountUser/Register.cshtml
@model VmStudentRegister
@{
    ViewData["Title"] = "Register";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h1>Register</h1>

<h4>RegisterSTUDENT</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-area="admin" asp-action="Register" asp-controller="AccountUser" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="@Model.ImageFile" class="form-label">Image</label>
                <input class="form-control" type="file" asp-for="@Model.ImageFile">
                <span asp-validation-for="@Model.ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Email" class="control-label">Email</label>
                <input asp-for="@Model.Email" class="form-control" />
                <span asp-validation-for="@Model.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Password" class="control-label"></label>
                <input asp-for="@Model.Password" class="form-control" />
                <span asp-validation-for="@Model.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.RepaetPassword" class="control-label"></label>
                <input asp-for="@Model.RepaetPassword" class="form-control" />
                <span asp-validation-for="@Model.RepaetPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Adı</label>
                <input asp-for="@Model.Name" class="form-control" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Soyadı</label>
                <input asp-for="@Model.Surname" class="form-control" />
                <span asp-validation-for="@Model.Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Atasının adı</label>
                <input asp-for="@Model.AtaAdi" class="form-control" />
                <span asp-validation-for="@Model.AtaAdi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Şəxsiyyət vəsiqəsinin seriya və nömrəsi</label>
                <input asp-for="@Model.PassportNumber" class="form-control" />
                <span asp-validation-for="@Model.PassportNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Cinsi</label>
                <select asp-for="@Model.Gender" class="form-control">
                    <option value="kisi">Kisi</option>
                    <option value="qadin">Qadin</option>
                </select>
                <span asp-validation-for="@Model.Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Adress</label>
                <input asp-for="@Model.Adress" class="form-control" />
                <span asp-validation-for="@Model.Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Telefon</label>
                <input type="tel" asp-for="@Model.Phone" class="form-control" />
                <span asp-validation-for="@Model.Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Təhsil növü</label>
                <select asp-for="@Model.Money" class="form-control">
                    <option value="free">Ödənişli</option>
                    <option value="Paid">Dövlət Hesabına</option>
                </select>
                <span asp-validation-for="@Model.Money" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Təhsil formasi</label>
                <select asp-for="@Model.FormEducation" class="form-control">
                    <option value="Eyani">Eyani</option>
                    <option value="Qiyabi">Qiyabi</option>
                </select>
                <span asp-validation-for="@Model.FormEducation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Doğum tarixi</label>
                <input type="date" asp-for="@Model.DateOfBirth" class="form-control" />
                <span asp-validation-for="@Model.DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Qebul olma tarixi</label>
                <input type="date" asp-for="@Model.DateOfCompletion" class="form-control" />
                <span asp-validation-for="@Model.DateOfCompletion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Bitirdiyi tarix</label>
                <input type="date" asp-for="@Model.AdmissionDate" class="form-control" />
                <span asp-validation-for="@Model.AdmissionDate" class="text-danger"></span>
            </div>
            <div class=" form-group">
                <label class="control-label">Fakulte</label>
                <select asp-for="@Model.FacultyId" class="form-control" id="facultyId" asp-items="@(new SelectList(@ViewBag.FacultyList,"Id","Name"))"></select>
            </div>
            <div class=" form-group">
                <label class="control-label">Ixtisas</label>
                <select asp-for="@Model.SpecialtyId" class="form-control" id="specialtyId"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Qrup</label>
                <select asp-for="@Model.GroupId" id="groupId" class="form-control"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Bolme</label>
                <select class="form-control" asp-for="@Model.EducationSectionId" asp-items="ViewBag.EducationSectionId"></select>
            </div>
            <select asp-for="@Model.IsAdmin">
                <option value="false">False</option>
            </select>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        GetSpecialty();
    })
    $("#facultyId").change(function () {
        GetSpecialty();
    });
    var GetSpecialty = function () {
         $.ajax({
            url: '@Url.Action("GetSpecialty", "AccountUser")',
            type: 'GET',
            data: {
                facultyId: $('#facultyId').val(),
            },
            success: function (data) {
                $('#specialtyId').find('option').remove()
                $(data).each(
                    function (index, item) {
                        $('#specialtyId').append('<option value="' + item.id + '">' + item.name + '</option>')
                        console.log(item)
                    });
            },
            error: function () {
            }
           });
    }

     $(document).ready(function () {
         GetGroup();
    })
    $("#specialtyId").change(function () {
        GetGroup();
    });
    var GetGroup = function () {
         $.ajax({
            url: '@Url.Action("GetGroup", "AccountUser")',
            type: 'GET',
            data: {
                specialtyId: $('#specialtyId').val(),
            },
            success: function (data) {
                $('#groupId').find('option').remove()
                $(data).each(
                    function (index, item) {
                        $('#groupId').append('<option value="' + item.id + '">' + item.name + '</option>')
                        console.log(item)
                    });
            },
            error: function () {
            }
           });
    }
</script>